version: '3.8'

services:
  api:
    build:
      context: .
      target: production
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - /opt/vault:/vault:rw
      - /var/log/obsidian-automation:/app/logs
      - /home/ubuntu/.ssh/vault_deploy_key:/home/appuser/.ssh/vault_deploy_key:ro
      - /home/ubuntu/.ssh/config:/home/appuser/.ssh/config:ro

    environment:
      - VAULT_PATH=/vault
      - LOG_LEVEL=WARNING
      - ENVIRONMENT=production
      - HOM=/home/appuser
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
