version: '3.8'

services:
  api:
    build:
      context: .
      target: development  # Uses development stage from Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount source code for live reloading during development
      - ./src:/app/src
      - ./tests:/app/tests
      # Mount vault if it exists locally (adjust path as needed)
      - ${VAULT_PATH:-../vault}:/vault
    environment:
      - VAULT_PATH=/vault
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=development
      # - API_KEY=dev-key-change-in-production
    # Restart policy for development convenience
    restart: unless-stopped
    # Health check matches the endpoint you already have
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
