#cloud-config
packages:
  - docker.io
  - docker-compose
  - git
  - awscli

users:
  - default
  - name: ubuntu
    groups: docker

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - snap install amazon-ssm-agent --classic
  - systemctl enable snap.amazon-ssm-agent.amazon-ssm-agent
  - systemctl start snap.amazon-ssm-agent.amazon-ssm-agent

  - git clone https://github.com/avivsarig/Obsidian-backend.git /opt/backend
  - chown -R ubuntu:ubuntu /opt/backend
  - cd /opt/backend && docker-compose -f docker-compose.prod.yml up -d --build
