#cloud-config
packages:
  - docker.io
  - docker-compose
  - git
  - awscli
  - nginx

users:
  - default
  - name: ubuntu
    groups: docker

write_files:
  - path: /etc/nginx/sites-available/obsidian-automation
    content: |
      server {
          listen 80;
          server_name _;

          location / {
              proxy_pass http://localhost:8000;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;

              # Health check optimization
              proxy_connect_timeout 5s;
              proxy_send_timeout 60s;
              proxy_read_timeout 60s;
          }
      }

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - snap install amazon-ssm-agent --classic
  - systemctl enable snap.amazon-ssm-agent.amazon-ssm-agent
  - systemctl start snap.amazon-ssm-agent.amazon-ssm-agent

  # Configure nginx
  - rm -f /etc/nginx/sites-enabled/default
  - ln -s /etc/nginx/sites-available/obsidian-automation /etc/nginx/sites-enabled/
  - systemctl enable nginx
  - systemctl start nginx

  # Deploy application
  - git clone https://github.com/avivsarig/Obsidian-backend.git /opt/backend
  - chown -R ubuntu:ubuntu /opt/backend
  - cd /opt/backend && docker-compose -f docker-compose.prod.yml up -d --build

  # Test and restart nginx after app is ready
  - sleep 30
  - systemctl reload nginx
