name: Validate
on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Structure
        run: |
          echo "Repository structure validation"
          ls -la
